### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by Jithu023** [mirthAI/CSA-Net#1]
I hope this message finds you well. I am currently working with your CSA-Net repository and have encountered an issue that I am unable to resolve. Could you please provide some guidance or direct me to the appropriate resources?
The issue that i face is an Index error while training.

Thank you for your assistance. Please fix this issue as soon as possible
![Screenshot (94)](https://github.com/user-attachments/assets/8a74f4b2-8e73-4ca2-8c08-1e335bad5a7e)

Best regards,
Jithu A K

**Comment by WHloveHZN** [comment]
Hello, I encountered the same issue. May I ask if you have resolved it? 
Best regards

**Comment by Jithu023** [comment]
No, not yet.

**Comment by WHloveHZN** [comment]
Thank you for the reply.

**Comment by amar-iitism** [comment]
I was unable to replicate the error; however, I have updated the code based on the attached screenshot. Could you please check if this resolves your issue?

**Comment by WHloveHZN** [comment]
The updated code resolved the issue, thank you very much.
